name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-ci:
    uses: zvonilkaRU/ci/.github/workflows/go-service.yml@main
    with:
      service: libs
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Unit tests
        run: go test ./... -count=1
        env:
          CI: "true"

  itest:
    name: ITest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Integration tests
        run: go test -tags itest ./... -count=1
        env:
          CI: "true"
